const $=s=>document.querySelector(s),fmt=n=>Number(n).toLocaleString('th-TH');
const SB_URL='https://pjzgoqbnbqwqacyyvzxa.supabase.co';
const SB_KEY='sb_publishable_J8tgwn1RxrQLU2OjF8dXFg_1ngKSdho';
const SESSION_KEY='nara2_session';
let currentProfile=null;
function getSession(){try{return JSON.parse(localStorage.getItem(SESSION_KEY)||'null')}catch{return null}}
function roleLabel(r){return {admin:'ผู้ดูแลระบบ',area_staff:'เจ้าหน้าที่เขตพื้นที่',school_admin:'ผู้ดูแลโรงเรียน',viewer:'ผู้ใช้งานทั่วไป'}[r]||r}
async function initAuth(){const s=getSession();if(!s?.access_token){location.href='login.html';return false}const r=await fetch(`${SB_URL}/rest/v1/profiles?id=eq.${s.user.id}&select=id,display_name,role,school_id`,{headers:{apikey:SB_KEY,Authorization:`Bearer ${s.access_token}`}});if(!r.ok){localStorage.removeItem(SESSION_KEY);location.href='login.html';return false}currentProfile=(await r.json())[0];if(!currentProfile){location.href='unauthorized.html';return false}const av=$('.avatar');if(av){av.textContent=(currentProfile.display_name||'U').slice(0,2);av.title=`${currentProfile.display_name||''} • ${roleLabel(currentProfile.role)}`;}const area=['admin','area_staff'].includes(currentProfile.role);if(!area){document.querySelectorAll('nav button').forEach(b=>{if(/งบประมาณ|รายงาน|ตั้งค่าระบบ/.test(b.textContent))b.style.display='none'})}if(currentProfile.role==='admin'){const nav=document.querySelector('nav');const b=document.createElement('button');b.innerHTML='👤 <span>จัดการผู้ใช้งาน</span>';b.onclick=()=>location.href='users.html';nav.appendChild(b)}const h=document.querySelector('.header-actions');if(h){const out=document.createElement('button');out.textContent='ออกจากระบบ';out.onclick=()=>{localStorage.removeItem(SESSION_KEY);location.href='login.html'};h.appendChild(out)}return true}
function authHeaders(){const s=getSession();return {apikey:SB_KEY,Authorization:`Bearer ${s?.access_token||SB_KEY}`}}
const fallback={kpi:{schools:117,students:25610,teachers:2482,area_staff:74},districts:[['สุคิริน',15],['แว้ง',27],['สุไหงปาดี',31],['สุไหงโก-ลก',13],['ตากใบ',31]],retirements:[[2569,17,5],[2570,19,6],[2571,21,6],[2572,25,7],[2573,22,6],[2574,18,6],[2575,15,5],[2576,12,4],[2577,10,4],[2578,9,3]],announcements:[['13 ก.ย. 2569','ระบบ NARA2 BIG DATA เริ่มใช้งานฐานข้อมูลออนไลน์'],['10 ก.ย. 2569','เปิดสำรวจข้อมูลนักเรียนรายบุคคล ปีการศึกษา 2569']]};
let data=fallback,retirements=fallback.retirements;
async function getTable(table,query=''){const r=await fetch(`${SB_URL}/rest/v1/${table}?${query}`,{headers:authHeaders()});if(!r.ok)throw new Error(table);return r.json()}
async function loadData(){try{const [k,d,r,a]=await Promise.all([getTable('kpi_snapshots','select=*&order=academic_year.desc&limit=1'),getTable('districts','select=name,school_count&order=id'),getTable('retirements','select=buddhist_year,teachers,support_staff&order=buddhist_year'),getTable('announcements','select=published_date,title&active=eq.true&order=published_date.desc&limit=5')]);data={kpi:k[0]||fallback.kpi,districts:d.map(x=>[x.name,x.school_count]),retirements:r.map(x=>[x.buddhist_year,x.teachers,x.support_staff]),announcements:a.map(x=>[new Date(x.published_date).toLocaleDateString('th-TH',{day:'numeric',month:'short',year:'numeric'}),x.title])};retirements=data.retirements;render();}catch(e){data=fallback;retirements=fallback.retirements;render()}}
function drawBars(canvas,labels,series){const ctx=canvas.getContext('2d'),W=canvas.width,H=canvas.height,p={l:46,r:18,t:20,b:46};ctx.clearRect(0,0,W,H);const max=Math.max(...series.flatMap(s=>s.values))*1.15||1;ctx.strokeStyle='#dfe8f3';ctx.fillStyle='#6a819e';ctx.font='12px Tahoma';for(let i=0;i<=4;i++){let y=p.t+(H-p.t-p.b)*i/4;ctx.beginPath();ctx.moveTo(p.l,y);ctx.lineTo(W-p.r,y);ctx.stroke();ctx.fillText(fmt(Math.round(max*(1-i/4))),4,y+4)}const gw=(W-p.l-p.r)/labels.length,bw=Math.min(18,gw/(series.length+1));labels.forEach((lab,i)=>{ctx.fillStyle='#607795';ctx.fillText(lab,p.l+i*gw+gw*.28,H-16);series.forEach((s,j)=>{let v=s.values[i],h=(H-p.t-p.b)*v/max,x=p.l+i*gw+gw*.2+j*(bw+4),y=H-p.b-h;ctx.fillStyle=s.color;ctx.fillRect(x,y,bw,h);if(series.length<=2){ctx.fillStyle='#24466f';ctx.font='11px Tahoma';ctx.fillText(v,x-1,y-5)}})});let lx=p.l;series.forEach(s=>{ctx.fillStyle=s.color;ctx.fillRect(lx,4,10,10);ctx.fillStyle='#526d8e';ctx.fillText(s.name,lx+15,13);lx+=100})}
function render(){const k=data.kpi,kpis=[['🏫','จำนวนโรงเรียน',k.schools,'โรงเรียน'],['👥','นักเรียนในสังกัด',k.students,'คน'],['🧑‍🏫','ครูในสังกัด',k.teachers,'คน'],['👤','บุคลากร สพป.นร.2',k.area_staff,'คน'],['🗺️','5 อำเภอ',k.schools,'โรงเรียน']];$('#kpis').innerHTML=kpis.map(x=>`<div class="kpi"><div class="icon">${x[0]}</div><div><h4>${x[1]}</h4><b>${fmt(x[2])}</b><small>${x[3]}</small></div></div>`).join('');$('#districtMap').innerHTML=data.districts.map(x=>`<div class="district"><span>${x[0]}</span><b>${x[1]}</b><small>โรงเรียน</small></div>`).join('');$('#donutTotal').textContent=fmt(k.teachers+k.area_staff);$('#teacherLegend').textContent=fmt(k.teachers)+' คน';$('#staffLegend').textContent=fmt(k.area_staff)+' คน';drawBars($('#trendCanvas'),['2565','2566','2567','2568','2569'],[{name:'นักเรียน',color:'#2f91f7',values:[23450,24102,24870,25148,k.students]},{name:'ครู',color:'#ff3f8b',values:[2301,2356,2420,2455,k.teachers]},{name:'บุคลากร',color:'#35b778',values:[62,66,68,72,k.area_staff]}]);drawBars($('#retireCanvas'),retirements.map(x=>x[0]),[{name:'ครู',color:'#2d8df6',values:retirements.map(x=>x[1])},{name:'สายสนับสนุน',color:'#ff4389',values:retirements.map(x=>x[2])}]);const totals=retirements.map(x=>x[1]+x[2]),sum=totals.reduce((a,b)=>a+b,0),sum3=totals.slice(0,3).reduce((a,b)=>a+b,0),pi=totals.indexOf(Math.max(...totals)),peak=retirements[pi];$('#sum10').textContent=fmt(sum);$('#sum3').textContent=fmt(sum3);$('#peakYear').textContent=peak[0];$('#peakCount').textContent=totals[pi]+' คน';$('#retireAnalysis').innerHTML=`<span>จุดสูงสุด: พ.ศ. ${peak[0]} จำนวน ${totals[pi]} คน</span><span>3 ปีข้างหน้า: ${sum3} คน</span><span>ข้อมูลผู้เกษียณชุดนี้ยังเป็นข้อมูลสาธิต</span>`;$('#news').innerHTML=data.announcements.map(x=>`<div class="item"><b>${x[0]}</b>${x[1]}</div>`).join('')}
(async()=>{if(!(await initAuth()))return;$('#editRetire').onclick=()=>{if(['admin','area_staff'].includes(currentProfile.role))$('#modal').classList.add('show');else location.href='unauthorized.html'};$('#closeModal').onclick=()=>$('#modal').classList.remove('show');$('#retireForm').onsubmit=e=>{e.preventDefault();alert('โครงแก้ไขข้อมูลพร้อมต่อยอดผ่านสิทธิ์ของผู้ดูแล/เขตพื้นที่');};await loadData()})();