const $=s=>document.querySelector(s),fmt=n=>Number(n).toLocaleString('th-TH');
const SB_URL='https://pjzgoqbnbqwqacyyvzxa.supabase.co';
const SB_KEY='sb_publishable_J8tgwn1RxrQLU2OjF8dXFg_1ngKSdho';
let currentProfile=null;
const fallback={kpi:{schools:117,students:25610,teachers:2482,area_staff:74},districts:[['สุคิริน',15],['แว้ง',27],['สุไหงปาดี',31],['สุไหงโก-ลก',13],['ตากใบ',31]],retirements:[[2569,17,5],[2570,19,6],[2571,21,6],[2572,25,7],[2573,22,6],[2574,18,6],[2575,15,5],[2576,12,4],[2577,10,4],[2578,9,3]],announcements:[['13 ก.ย. 2569','ระบบ NARA2 BIG DATA เริ่มใช้งานฐานข้อมูลออนไลน์'],['10 ก.ย. 2569','เปิดสำรวจข้อมูลนักเรียนรายบุคคล ปีการศึกษา 2569']]};
let data=fallback,retirements=fallback.retirements;
function apiHeaders(){const s=getSession();return {apikey:SB_KEY,Authorization:`Bearer ${s?.access_token||SB_KEY}`}}
async function getTable(table,query=''){const r=await fetch(`${SB_URL}/rest/v1/${table}?${query}`,{headers:apiHeaders()});if(!r.ok)throw new Error(table);return r.json()}
async function initAccess(){const s=getSession();if(s?.access_token){try{currentProfile=await getMyProfile()}catch{currentProfile=null}}document.querySelectorAll('.manage-only,.admin-only,.area-only').forEach(el=>el.style.display=currentProfile?.role==='admin'?'':'none');const ua=$('#userActions'),av=$('#avatar');if(currentProfile){if(av){av.textContent=(currentProfile.display_name||'ผ').slice(0,2);av.title=`${currentProfile.display_name||''} • ${roleLabel(currentProfile.role)}`;}ua.innerHTML=`<span class="user-role">${roleLabel(currentProfile.role)}</span><button class="login-btn" id="logoutBtn">ออกจากระบบ</button>`;$('#logoutBtn').onclick=signOut}else{if(av){av.textContent='ผู้';av.title='ผู้เข้าชมทั่วไป'}ua.innerHTML='<button class="login-btn" onclick="location.href=\'login.html\'">เข้าสู่ระบบผู้ดูแล</button>'}}
async function loadData(){try{const [k,d,r,a]=await Promise.all([getTable('kpi_snapshots','select=*&order=academic_year.desc&limit=1'),getTable('districts','select=name,school_count&order=id'),getTable('retirements','select=buddhist_year,teachers,support_staff&order=buddhist_year'),getTable('announcements','select=published_date,title&active=eq.true&order=published_date.desc&limit=5')]);data={kpi:k[0]||fallback.kpi,districts:d.map(x=>[x.name,x.school_count]),retirements:r.map(x=>[x.buddhist_year,x.teachers,x.support_staff]),announcements:a.map(x=>[new Date(x.published_date).toLocaleDateString('th-TH',{day:'numeric',month:'short',year:'numeric'}),x.title])};retirements=data.retirements;render()}catch(e){console.warn('ใช้ข้อมูลสำรอง',e);data=fallback;retirements=fallback.retirements;render()}}
function drawBars(canvas,labels,series){if(!canvas)return;const ctx=canvas.getContext('2d'),W=canvas.width,H=canvas.height,p={l:46,r:18,t:20,b:46};ctx.clearRect(0,0,W,H);const max=Math.max(...series.flatMap(s=>s.values))*1.15||1;ctx.strokeStyle='#efe5eb';ctx.fillStyle='#7f8796';ctx.font='12px Tahoma';for(let i=0;i<=4;i++){let y=p.t+(H-p.t-p.b)*i/4;ctx.beginPath();ctx.moveTo(p.l,y);ctx.lineTo(W-p.r,y);ctx.stroke();ctx.fillText(fmt(Math.round(max*(1-i/4))),4,y+4)}const gw=(W-p.l-p.r)/labels.length,bw=Math.min(18,gw/(series.length+1));labels.forEach((lab,i)=>{ctx.fillStyle='#6b7382';ctx.fillText(lab,p.l+i*gw+gw*.28,H-16);series.forEach((s,j)=>{let v=s.values[i],h=(H-p.t-p.b)*v/max,x=p.l+i*gw+gw*.2+j*(bw+4),y=H-p.b-h;ctx.fillStyle=s.color;ctx.fillRect(x,y,bw,h);if(series.length<=2){ctx.fillStyle='#3c4556';ctx.font='11px Tahoma';ctx.fillText(v,x-1,y-5)}})});let lx=p.l;series.forEach(s=>{ctx.fillStyle=s.color;ctx.fillRect(lx,4,10,10);ctx.fillStyle='#626b7b';ctx.fillText(s.name,lx+15,13);lx+=100})}
function render(){const k=data.kpi,kpis=[['🏫','จำนวนโรงเรียน',k.schools,'โรงเรียน'],['👥','นักเรียนในสังกัด',k.students,'คน'],['🧑‍🏫','ครูในสังกัด',k.teachers,'คน'],['👤','บุคลากร สพป.นร.2',k.area_staff,'คน'],['🗺️','พื้นที่รับผิดชอบ',5,'อำเภอ']];$('#kpis').innerHTML=kpis.map(x=>`<div class="kpi"><div class="icon">${x[0]}</div><div><h4>${x[1]}</h4><b>${fmt(x[2])}</b><small>${x[3]}</small></div></div>`).join('');$('#districtMap').innerHTML=data.districts.map(x=>`<div class="district"><span>${x[0]}</span><b>${x[1]}</b><small>โรงเรียน</small></div>`).join('');$('#donutTotal').textContent=fmt(k.teachers+k.area_staff);$('#teacherLegend').textContent=fmt(k.teachers)+' คน';$('#staffLegend').textContent=fmt(k.area_staff)+' คน';drawBars($('#trendCanvas'),['2565','2566','2567','2568','2569'],[{name:'นักเรียน',color:'#ef3f82',values:[23450,24102,24870,25148,k.students]},{name:'ครู',color:'#7c49bd',values:[2301,2356,2420,2455,k.teachers]},{name:'บุคลากร',color:'#32b9e9',values:[62,66,68,72,k.area_staff]}]);drawBars($('#retireCanvas'),retirements.map(x=>x[0]),[{name:'ครู',color:'#ef3f82',values:retirements.map(x=>x[1])},{name:'สายสนับสนุน',color:'#ffad29',values:retirements.map(x=>x[2])}]);const totals=retirements.map(x=>x[1]+x[2]),sum=totals.reduce((a,b)=>a+b,0),sum3=totals.slice(0,3).reduce((a,b)=>a+b,0),pi=totals.indexOf(Math.max(...totals)),peak=retirements[pi];$('#sum10').textContent=fmt(sum);$('#sum3').textContent=fmt(sum3);$('#peakYear').textContent=peak?.[0]||'-';$('#peakCount').textContent=peak?totals[pi]+' คน':'-';$('#retireAnalysis').innerHTML=peak?`<span>จุดสูงสุด: พ.ศ. ${peak[0]} จำนวน ${totals[pi]} คน</span><span>3 ปีข้างหน้า: ${sum3} คน</span><span>ข้อมูลผู้เกษียณชุดนี้ยังเป็นข้อมูลสาธิต</span>`:'';$('#news').innerHTML=data.announcements.map(x=>`<div class="item"><b>${x[0]}</b>${x[1]}</div>`).join('')}
function initUi(){const menu=$('#mobileMenuBtn'),side=$('#sidebar');if(menu&&side){menu.onclick=()=>side.classList.toggle('mobile-open');document.addEventListener('click',e=>{if(innerWidth<=700&&side.classList.contains('mobile-open')&&!side.contains(e.target)&&e.target!==menu)side.classList.remove('mobile-open')})}const edit=$('#editRetire'),close=$('#closeModal'),form=$('#retireForm');if(edit)edit.onclick=()=>{if(currentProfile?.role==='admin')location.href='section.html?view=retirements';else location.href='login.html'};if(close)close.onclick=()=>$('#modal').classList.remove('show');if(form)form.onsubmit=e=>{e.preventDefault()}}
(async()=>{await initAccess();initUi();await loadData()})();