let naraMainChart=null,naraDonutChart=null,naraDashBusy=false;
const BLUE=['#0b4f9c','#2d6fb7','#5a8fc7','#86acd4','#b3c9e2','#d8e4f0'];
function nsum(a,k){return a.reduce((s,x)=>s+(Number(x?.[k])||0),0)}
function groupCount(a,k){const m={};a.forEach(x=>{const v=(x?.[k]??'ไม่ระบุ')||'ไม่ระบุ';m[v]=(m[v]||0)+1});return m}
function groupSum(a,k,v){const m={};a.forEach(x=>{const key=(x?.[k]??'ไม่ระบุ')||'ไม่ระบุ';m[key]=(m[key]||0)+(Number(x?.[v])||0)});return m}
function top(obj,n=12){return Object.entries(obj).sort((a,b)=>b[1]-a[1]).slice(0,n)}
function barCfg(labels,values,label){return {type:'bar',data:{labels,datasets:[{label,data:values,backgroundColor:'#2d6fb7',borderColor:'#0b4f9c',borderWidth:1,borderRadius:5}]},options:{responsive:true,maintainAspectRatio:false,interaction:{mode:'index',intersect:false},plugins:{legend:{display:false}},scales:{x:{grid:{display:false}},y:{beginAtZero:true,grid:{color:'#e8eef5'}}}}}}
function doughnutCfg(labels,values,label){return {type:'doughnut',data:{labels,datasets:[{label,data:values,backgroundColor:BLUE,borderColor:'#fff',borderWidth:2}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:'bottom',labels:{boxWidth:12,usePointStyle:true}}}}}}
function lineMultiCfg(labels,datasets){return {type:'line',data:{labels,datasets:datasets.map((d,i)=>({label:d.label,data:d.data,borderColor:BLUE[i%BLUE.length],backgroundColor:BLUE[i%BLUE.length],borderWidth:2,tension:.3,pointRadius:3,fill:false}))},options:{responsive:true,maintainAspectRatio:false,interaction:{mode:'index',intersect:false},plugins:{legend:{position:'bottom'}},scales:{x:{grid:{display:false}},y:{beginAtZero:false,grid:{color:'#e8eef5'}}}}}}
function draw(primary,secondary){if(!window.Chart)return;const a=document.getElementById('mainChart'),b=document.getElementById('donutChart');if(naraMainChart)naraMainChart.destroy();if(naraDonutChart)naraDonutChart.destroy();naraMainChart=new Chart(a,primary);naraDonutChart=new Chart(b,secondary)}
function insights(lines){const box=document.getElementById('insights');box.innerHTML=lines.filter(Boolean).slice(0,4).map(x=>`<div class="insight">${x}</div>`).join('')}
function setCards(items){const box=document.getElementById('cards');if(!box)return;box.innerHTML=items.map(([label,value,unit=''])=>`<div class="mini"><small>${label}</small><b>${Number(value||0).toLocaleString('th-TH')}</b><span>${unit}</span></div>`).join('')}
async function rowsNow(){if(view==='overview')return await pub('schools','select=school_code,name,student_count,teacher_count,districts(name)&order=name');return Array.isArray(filtered)?filtered:[]}
async function renderInteractiveDashboard(){if(naraDashBusy)return;naraDashBusy=true;try{const a=await rowsNow();let main,donut,ins=[];const ct=document.getElementById('chartTitle'),dt=document.getElementById('donutTitle');
if(view==='overview'||view==='schools'){
 const byDistrict={};a.forEach(x=>{const d=x.district||x.districts?.name||'ไม่ระบุ';byDistrict[d]=(byDistrict[d]||0)+1});const e=top(byDistrict,10);main=barCfg(e.map(x=>x[0]),e.map(x=>x[1]),'จำนวนโรงเรียน');const stu={};a.forEach(x=>{const d=x.district||x.districts?.name||'ไม่ระบุ';stu[d]=(stu[d]||0)+(Number(x.student_count)||0)});const d2=top(stu,10);donut=doughnutCfg(d2.map(x=>x[0]),d2.map(x=>x[1]),'นักเรียน');ct.textContent='จำนวนโรงเรียนรายอำเภอ';dt.textContent='สัดส่วนนักเรียนรายอำเภอ';setCards([['โรงเรียน',a.length,' แห่ง'],['นักเรียน',nsum(a,'student_count'),' คน'],['ครู',nsum(a,'teacher_count'),' คน'],['อำเภอ',Object.keys(byDistrict).length,' อำเภอ']]);ins=[`โรงเรียนในชุดข้อมูล ${a.length.toLocaleString('th-TH')} แห่ง`,`นักเรียนรวม ${nsum(a,'student_count').toLocaleString('th-TH')} คน`,`ครูรวม ${nsum(a,'teacher_count').toLocaleString('th-TH')} คน`]
}else if(view==='students'){
 const grade=top(groupCount(a,'grade_level'),15),gender=top(groupCount(a,'gender'),8);main=barCfg(grade.map(x=>x[0]),grade.map(x=>x[1]),'นักเรียน');donut=doughnutCfg(gender.map(x=>x[0]),gender.map(x=>x[1]),'เพศ');ct.textContent='นักเรียนแยกระดับชั้น';dt.textContent='สัดส่วนนักเรียนตามเพศ';setCards([['นักเรียน',a.length,' ราย'],['ระดับชั้น',grade.length,' ระดับ'],['โรงเรียน',new Set(a.map(x=>x.school_id)).size,' แห่ง'],['ปีข้อมูล',new Set(a.map(x=>x.academic_year)).size,' ปี']]);ins=[grade[0]?`ระดับชั้นที่มีข้อมูลมากที่สุด ${grade[0][0]} ${grade[0][1]} ราย`:null,gender[0]?`กลุ่มเพศที่มีจำนวนสูงสุด ${gender[0][0]} ${gender[0][1]} ราย`:null]
}else if(view==='staff'){
 const total=nsum(a,'total_personnel'),male=nsum(a,'male_count'),female=nsum(a,'female_count'),shortage=nsum(a,'shortage_count'),surplus=nsum(a,'surplus_count');const manpower=[['อัตราที่ควรมี',nsum(a,'required_teacher_count')],['ครูที่มี',nsum(a,'current_teacher_count')],['ขาด',shortage],['เกิน',surplus]];main=barCfg(manpower.map(x=>x[0]),manpower.map(x=>x[1]),'อัตรากำลัง');donut=doughnutCfg(['ชาย','หญิง'],[male,female],'เพศ');ct.textContent='ภาพรวมอัตรากำลังครู';dt.textContent='สัดส่วนเพศบุคลากร';setCards([['บุคลากรรวม',total,' คน'],['โรงเรียน',a.length,' แห่ง'],['ขาดอัตรา',shortage,' อัตรา'],['เกินอัตรา',surplus,' อัตรา']]);const ranks=[['ไม่มีวิทยฐานะ',nsum(a,'rank_none_count')],['ชำนาญการ',nsum(a,'rank_professional_count')],['ชำนาญการพิเศษ',nsum(a,'rank_senior_professional_count')],['เชี่ยวชาญ',nsum(a,'rank_expert_count')],['เชี่ยวชาญพิเศษ',nsum(a,'rank_senior_expert_count')]];const maxRank=ranks.sort((x,y)=>y[1]-x[1])[0];ins=[`แนวโน้มเกษียณ 1 ปี ${nsum(a,'retire_next_1y').toLocaleString('th-TH')} คน`,`แนวโน้มเกษียณ 3 ปี ${nsum(a,'retire_next_3y').toLocaleString('th-TH')} คน`,`แนวโน้มเกษียณ 5 ปี ${nsum(a,'retire_next_5y').toLocaleString('th-TH')} คน`,maxRank?`วิทยฐานะที่มีจำนวนมากที่สุด: ${maxRank[0]} ${maxRank[1].toLocaleString('th-TH')} คน`:null]
}else if(view==='retirements'){
 const s=[...a].sort((x,y)=>(+x.buddhist_year)-(+y.buddhist_year));main=lineMultiCfg(s.map(x=>x.buddhist_year),[{label:'รวมผู้เกษียณ',data:s.map(x=>(+x.teachers||0)+(+x.support_staff||0))}]);donut=doughnutCfg(['ครู','สายสนับสนุน'],[nsum(a,'teachers'),nsum(a,'support_staff')],'รวม');ct.textContent='แนวโน้มผู้เกษียณรายปี';dt.textContent='สัดส่วนผู้เกษียณตามประเภท';const totals=s.map(x=>(+x.teachers||0)+(+x.support_staff||0));setCards([['รวมช่วงข้อมูล',totals.reduce((p,c)=>p+c,0),' คน'],['ครู',nsum(a,'teachers'),' คน'],['สายสนับสนุน',nsum(a,'support_staff'),' คน'],['ปีข้อมูล',s.length,' ปี']]);ins=['ใช้ประกอบการวางแผนอัตรากำลังล่วงหน้า']
}else if(view==='achievement'){
 const years=[...new Set(a.map(x=>+x.academic_year).filter(Boolean))].sort((x,y)=>x-y),tests=['O-NET','NT','RT','PISA'];const datasets=tests.map(t=>({label:t,data:years.map(y=>{const z=a.filter(x=>+x.academic_year===y&&(x.test_type||x.test_name)===t);return z.length?Number((z.reduce((s,x)=>s+(+x.average_score||0),0)/z.length).toFixed(2)):null})}));main=lineMultiCfg(years,datasets);const testCount=tests.map(t=>a.filter(x=>(x.test_type||x.test_name)===t).length);donut=doughnutCfg(tests,testCount,'ประเภทสอบ');ct.textContent='เปรียบเทียบคะแนนเฉลี่ย O-NET / NT / RT / PISA รายปี';dt.textContent='สัดส่วนข้อมูลตามประเภทการทดสอบ';const avg=a.length?nsum(a,'average_score')/a.length:0,pred=a.filter(x=>x.predicted_score!=null);const pavg=pred.length?nsum(pred,'predicted_score')/pred.length:0;setCards([['คะแนนเฉลี่ยรวม',avg.toFixed(2),' คะแนน'],['คาดการณ์เฉลี่ย',pavg.toFixed(2),' คะแนน'],['โรงเรียน',new Set(a.map(x=>x.school_id)).size,' แห่ง'],['รายการผลสอบ',a.length,' รายการ']]);const latestYear=years.at(-1),prevYear=years.at(-2);let trend='ยังไม่มีข้อมูลเพียงพอสำหรับเทียบแนวโน้ม';if(latestYear&&prevYear){const av=y=>{const z=a.filter(x=>+x.academic_year===y);return z.length?nsum(z,'average_score')/z.length:0};const diff=av(latestYear)-av(prevYear);trend=`คะแนนเฉลี่ยปี ${latestYear} ${diff>=0?'เพิ่มขึ้น':'ลดลง'} ${Math.abs(diff).toFixed(2)} คะแนนจากปีก่อน`;}ins=[trend,'กดชื่อโรงเรียนในตารางเพื่อดูรายละเอียดและตารางเปรียบเทียบรายปี','การคาดการณ์เป็นแนวโน้มเพื่อประกอบการวางแผน ไม่ใช่ผลสอบจริงในอนาคต']
}else if(view==='dropout'){
 const risk=top(groupCount(a,'risk_level'),10),status=top(groupCount(a,'case_status'),10);main=barCfg(risk.map(x=>x[0]),risk.map(x=>x[1]),'กรณี');donut=doughnutCfg(status.map(x=>x[0]),status.map(x=>x[1]),'สถานะ');ct.textContent='กรณีติดตามแยกระดับความเสี่ยง';dt.textContent='สถานะการติดตาม';setCards([['กรณีทั้งหมด',a.length,' รายการ'],['โรงเรียน',new Set(a.map(x=>x.school_id)).size,' แห่ง'],['ระดับความเสี่ยง',risk.length,' ระดับ'],['สถานะ',status.length,' สถานะ']]);ins=[risk[0]?`ระดับที่พบมากที่สุด ${risk[0][0]} ${risk[0][1]} ราย`:null,status[0]?`สถานะหลัก ${status[0][0]}`:null]
}else if(view==='budgets'){
 const byType=top(groupSum(a,'budget_type','allocated_amount'),12);main=barCfg(byType.map(x=>x[0]),byType.map(x=>x[1]),'งบจัดสรร');const allocated=nsum(a,'allocated_amount'),spent=nsum(a,'spent_amount'),balance=Math.max(0,allocated-spent);donut=doughnutCfg(['ใช้จ่าย','คงเหลือ'],[spent,balance],'งบประมาณ');ct.textContent='งบจัดสรรตามประเภทงบ';dt.textContent='สัดส่วนการใช้จ่าย';setCards([['จัดสรร',allocated,' บาท'],['ใช้จ่าย',spent,' บาท'],['คงเหลือ',balance,' บาท'],['โครงการ',a.length,' รายการ']]);ins=[allocated?`ใช้จ่ายแล้ว ${(spent/allocated*100).toFixed(1)}% ของงบจัดสรร`:null]
}else if(view==='ict'){
 const devices=[['คอมพิวเตอร์',nsum(a,'computer_count')],['โน้ตบุ๊ก',nsum(a,'notebook_count')],['CCTV',nsum(a,'cctv_count')],['เครื่องพิมพ์',nsum(a,'printer_count')],['สแกนเนอร์',nsum(a,'scanner_count')],['เครื่องถ่ายเอกสาร',nsum(a,'copier_count')],['TV',nsum(a,'tv_count')],['UPS',nsum(a,'ups_count')]];main=barCfg(devices.map(x=>x[0]),devices.map(x=>x[1]),'จำนวนอุปกรณ์');donut=doughnutCfg(['CCTV ใช้ได้','CCTV ใช้ไม่ได้','TV ใช้ได้','TV ใช้ไม่ได้'],[nsum(a,'cctv_working_count'),nsum(a,'cctv_broken_count'),nsum(a,'tv_working_count'),nsum(a,'tv_broken_count')],'สถานะอุปกรณ์');ct.textContent='สินทรัพย์และอุปกรณ์ ICT';dt.textContent='สถานะ CCTV และ TV';const avgSpeed=a.length?nsum(a,'internet_speed_mbps')/a.length:0,monthly=nsum(a,'monthly_internet_cost');setCards([['คอม+โน้ตบุ๊ก',nsum(a,'computer_count')+nsum(a,'notebook_count'),' เครื่อง'],['CCTV',nsum(a,'cctv_count'),' ตัว'],['คู่สายอินเทอร์เน็ต',nsum(a,'internet_lines'),' คู่สาย'],['ค่าเน็ตรายเดือน',monthly,' บาท']]);ins=[`ความเร็วอินเทอร์เน็ตเฉลี่ย ${avgSpeed.toFixed(1)} Mbps`,`งบจัดซื้ออุปกรณ์ในชุดข้อมูล ${nsum(a,'purchase_budget').toLocaleString('th-TH')} บาท`,`CCTV ใช้งานไม่ได้ ${nsum(a,'cctv_broken_count').toLocaleString('th-TH')} ตัว`,`TV ใช้งานไม่ได้ ${nsum(a,'tv_broken_count').toLocaleString('th-TH')} เครื่อง`]
}else if(view==='documents'){
 const cat=top(groupCount(a,'category'),12);main=barCfg(cat.map(x=>x[0]),cat.map(x=>x[1]),'เอกสาร');donut=doughnutCfg(['เผยแพร่','ไม่เผยแพร่'],[a.filter(x=>x.active).length,a.filter(x=>!x.active).length],'สถานะ');ct.textContent='เอกสารแยกตามหมวด';dt.textContent='สถานะการเผยแพร่';setCards([['เอกสาร',a.length,' รายการ'],['หมวด',cat.length,' หมวด'],['เผยแพร่',a.filter(x=>x.active).length,' รายการ'],['ไม่เผยแพร่',a.filter(x=>!x.active).length,' รายการ']]);ins=[cat[0]?`หมวดที่มีเอกสารมากที่สุด ${cat[0][0]}`:null]
}else if(view==='announcements'){
 const byMonth={};a.forEach(x=>{const d=String(x.published_date||'').slice(0,7)||'ไม่ระบุ';byMonth[d]=(byMonth[d]||0)+1});const e=Object.entries(byMonth).sort((x,y)=>x[0].localeCompare(y[0]));main=lineMultiCfg(e.map(x=>x[0]),[{label:'ข่าว',data:e.map(x=>x[1])}]);donut=doughnutCfg(['เผยแพร่','ไม่เผยแพร่'],[a.filter(x=>x.active).length,a.filter(x=>!x.active).length],'สถานะ');ct.textContent='จำนวนข่าวตามเดือน';dt.textContent='สถานะข่าว';setCards([['ข่าวทั้งหมด',a.length,' รายการ'],['เดือนข้อมูล',e.length,' เดือน'],['เผยแพร่',a.filter(x=>x.active).length,' รายการ'],['ไม่เผยแพร่',a.filter(x=>!x.active).length,' รายการ']]);ins=['กราฟและตัวเลขจะปรับตามคำค้นหาและตัวกรองอัตโนมัติ']
}else{return}
draw(main,donut);insights(ins)}catch(e){console.warn('dashboard',e)}finally{naraDashBusy=false}}
const rc=document.getElementById('recordCount');if(rc)new MutationObserver(()=>{clearTimeout(window.__naraDashTimer);window.__naraDashTimer=setTimeout(renderInteractiveDashboard,80)}).observe(rc,{childList:true,subtree:true,characterData:true});['searchBox','districtFilter','yearFilter'].forEach(id=>{const el=document.getElementById(id);if(el){el.addEventListener('input',()=>setTimeout(renderInteractiveDashboard,30));el.addEventListener('change',()=>setTimeout(renderInteractiveDashboard,30))}});setTimeout(renderInteractiveDashboard,650);