(()=>{
  const PALETTE=['#155fa8','#3f7fbd','#6c9dca','#8fb5d8','#b7cee4','#d7e5f2'];
  if(window.Chart){
    Chart.defaults.color='#6d7d8f';
    Chart.defaults.borderColor='#e6edf5';
    Chart.defaults.font.family='Tahoma, Noto Sans Thai, sans-serif';
  }
  window.barCfg=function(labels,values,label){return {type:'bar',data:{labels,datasets:[{label,data:values,backgroundColor:labels.map((_,i)=>PALETTE[i%PALETTE.length]),borderColor:labels.map((_,i)=>PALETTE[i%PALETTE.length]),borderWidth:1,borderRadius:6}]},options:{responsive:true,maintainAspectRatio:false,interaction:{mode:'index',intersect:false},plugins:{legend:{display:false},tooltip:{backgroundColor:'#24364b',titleColor:'#fff',bodyColor:'#fff',padding:10}},scales:{x:{grid:{display:false},ticks:{color:'#7a899a'}},y:{beginAtZero:true,grid:{color:'#e8eef5'},ticks:{color:'#7a899a'}}}}}};
  window.doughnutCfg=function(labels,values,label){return {type:'doughnut',data:{labels,datasets:[{label,data:values,backgroundColor:labels.map((_,i)=>PALETTE[i%PALETTE.length]),borderColor:'#fff',borderWidth:3,hoverOffset:6}]},options:{responsive:true,maintainAspectRatio:false,cutout:'70%',plugins:{legend:{position:'bottom',labels:{boxWidth:10,usePointStyle:true,color:'#6d7d8f',padding:14}},tooltip:{backgroundColor:'#24364b',titleColor:'#fff',bodyColor:'#fff',padding:10}}}}};
  window.lineMultiCfg=function(labels,datasets){return {type:'line',data:{labels,datasets:datasets.map((d,i)=>({label:d.label,data:d.data,borderColor:PALETTE[i%PALETTE.length],backgroundColor:PALETTE[i%PALETTE.length],borderWidth:2.25,tension:.32,pointRadius:3,pointHoverRadius:5,pointBackgroundColor:'#fff',pointBorderWidth:2,fill:false}))},options:{responsive:true,maintainAspectRatio:false,interaction:{mode:'index',intersect:false},plugins:{legend:{position:'bottom',labels:{usePointStyle:true,boxWidth:10,color:'#6d7d8f',padding:14}},tooltip:{backgroundColor:'#24364b',titleColor:'#fff',bodyColor:'#fff',padding:10}},scales:{x:{grid:{display:false},ticks:{color:'#7a899a'}},y:{beginAtZero:false,grid:{color:'#e8eef5'},ticks:{color:'#7a899a'}}}}}};
  setTimeout(()=>{if(typeof window.renderInteractiveDashboard==='function')window.renderInteractiveDashboard()},120);
})();