let naraMainChart=null,naraDonutChart=null,naraDashBusy=false;
const BLUE=['#0b4f9c','#2d6fb7','#5a8fc7','#86acd4','#b3c9e2','#d8e4f0'];
const BLUE2=['#123a63','#0b4f9c','#2d6fb7','#5a8fc7','#86acd4','#b3c9e2'];
function nsum(a,k){return a.reduce((s,x)=>s+(Number(x?.[k])||0),0)}
function groupCount(a,k){const m={};a.forEach(x=>{const v=(x?.[k]??'ไม่ระบุ')||'ไม่ระบุ';m[v]=(m[v]||0)+1});return m}
function groupSum(a,k,v){const m={};a.forEach(x=>{const key=(x?.[k]??'ไม่ระบุ')||'ไม่ระบุ';m[key]=(m[key]||0)+(Number(x?.[v])||0)});return m}
function entriesTop(obj,n=12){return Object.entries(obj).sort((a,b)=>b[1]-a[1]).slice(0,n)}
function chartBase(type,labels,values,label){return {type,data:{labels,datasets:[{label,data:values,backgroundColor:BLUE,borderColor:'#0b4f9c',borderWidth:type==='line'?2:1,tension:.28,fill:false,borderRadius:type==='bar'?5:0}]},options:{responsive:true,maintainAspectRatio:false,interaction:{mode:'index',intersect:false},plugins:{legend:{display:type==='doughnut',position:'bottom',labels:{boxWidth:12,usePointStyle:true}},tooltip:{enabled:true}},scales:type==='doughnut'?{}:{x:{grid:{display:false},ticks:{maxRotation:35,minRotation:0}},y:{beginAtZero:true,grid:{color:'#e8eef5'}}}}}}
function drawDashboard(primary,secondary){if(!window.Chart)return;const a=document.getElementById('mainChart'),b=document.getElementById('donutChart');if(naraMainChart)naraMainChart.destroy();if(naraDonutChart)naraDonutChart.destroy();naraMainChart=new Chart(a,primary);naraDonutChart=new Chart(b,secondary)}
function insightLines(lines){const box=document.getElementById('insights');box.innerHTML=lines.filter(Boolean).slice(0,3).map(x=>`<div class="insight">${x}</div>`).join('')}
async function currentDashboardRows(){try{if(view==='overview')return await pub('schools','select=school_code,name,student_count,teacher_count,districts(name)&order=name');return Array.isArray(filtered)?filtered:[]}catch{return Array.isArray(filtered)?filtered:[]}}
function districtName(x){return x.district||x.districts?.name||x.schools?.districts?.name||x.schools?.name||'ไม่ระบุ'}
function schoolName(x){return x.school||x.schools?.name||'ไม่ระบุ'}
async function renderInteractiveDashboard(){if(naraDashBusy)return;naraDashBusy=true;try{const a=await currentDashboardRows();let main,donut,ins=[];const chartTitle=document.getElementById('chartTitle'),donutTitle=document.getElementById('donutTitle');
if(view==='overview'||view==='schools'){
 const ds={};a.forEach(x=>{const d=districtName(x);ds[d]=(ds[d]||0)+1});const e=entriesTop(ds,10);main=chartBase('bar',e.map(x=>x[0]),e.map(x=>x[1]),'จำนวนโรงเรียน');const studentByDistrict={};a.forEach(x=>{const d=districtName(x);studentByDistrict[d]=(studentByDistrict[d]||0)+(Number(x.student_count)||0)});const d2=entriesTop(studentByDistrict,10);donut=chartBase('doughnut',d2.map(x=>x[0]),d2.map(x=>x[1]),'นักเรียน');chartTitle.textContent='จำนวนโรงเรียนรายอำเภอ';donutTitle.textContent='สัดส่วนนักเรียนรายอำเภอ';ins=[`แสดง ${a.length.toLocaleString('th-TH')} โรงเรียน`,`นักเรียนรวม ${nsum(a,'student_count').toLocaleString('th-TH')} คน`,`ครูรวม ${nsum(a,'teacher_count').toLocaleString('th-TH')} คน`]
}else if(view==='students'){
 const grade=entriesTop(groupCount(a,'grade_level'),15),gender=entriesTop(groupCount(a,'gender'),8);main=chartBase('bar',grade.map(x=>x[0]),grade.map(x=>x[1]),'นักเรียน');donut=chartBase('doughnut',gender.map(x=>x[0]),gender.map(x=>x[1]),'เพศ');chartTitle.textContent='นักเรียนแยกระดับชั้น';donutTitle.textContent='สัดส่วนนักเรียนตามเพศ';ins=[`นักเรียนในชุดข้อมูล ${a.length.toLocaleString('th-TH')} ราย`,`ระดับชั้นที่พบ ${grade.length} ระดับ`,gender[0]?`กลุ่มสูงสุด ${gender[0][0]} ${gender[0][1].toLocaleString('th-TH')} ราย`:null]
}else if(view==='staff'){
 const pos=entriesTop(groupCount(a,'position'),12),typ=entriesTop(groupCount(a,'staff_type'),8);main=chartBase('bar',pos.map(x=>x[0]),pos.map(x=>x[1]),'บุคลากร');donut=chartBase('doughnut',typ.map(x=>x[0]),typ.map(x=>x[1]),'ประเภท');chartTitle.textContent='บุคลากรแยกตามตำแหน่ง';donutTitle.textContent='สัดส่วนประเภทบุคลากร';ins=[`บุคลากร ${a.length.toLocaleString('th-TH')} ราย`,pos[0]?`ตำแหน่งสูงสุด ${pos[0][0]} ${pos[0][1]} ราย`:null,typ[0]?`ประเภทหลัก ${typ[0][0]}`:null]
}else if(view==='retirements'){
 const s=[...a].sort((x,y)=>(+x.buddhist_year)-(+y.buddhist_year));main={...chartBase('line',s.map(x=>x.buddhist_year),s.map(x=>(+x.teachers||0)+(+x.support_staff||0)),'รวมผู้เกษียณ')};donut=chartBase('doughnut',['ครู','สายสนับสนุน'],[nsum(a,'teachers'),nsum(a,'support_staff')],'รวม');chartTitle.textContent='แนวโน้มผู้เกษียณรายปี';donutTitle.textContent='สัดส่วนผู้เกษียณตามประเภท';const totals=s.map(x=>(+x.teachers||0)+(+x.support_staff||0)),mx=Math.max(0,...totals),mi=totals.indexOf(mx);ins=[`รวมทั้งช่วง ${totals.reduce((p,c)=>p+c,0).toLocaleString('th-TH')} คน`,s[mi]?`สูงสุด พ.ศ. ${s[mi].buddhist_year} จำนวน ${mx} คน`:null,'ใช้วางแผนอัตรากำลังล่วงหน้า']
}else if(view==='achievement'){
 const subjects=entriesTop(groupSum(a,'subject','average_score'),12);const counts=groupCount(a,'subject');subjects.forEach(x=>x[1]=x[1]/(counts[x[0]]||1));main=chartBase('bar',subjects.map(x=>x[0]),subjects.map(x=>Number(x[1].toFixed(2))),'คะแนนเฉลี่ย');const tests=entriesTop(groupCount(a,'test_name'),8);donut=chartBase('doughnut',tests.map(x=>x[0]),tests.map(x=>x[1]),'รายการ');chartTitle.textContent='คะแนนเฉลี่ยรายวิชา';donutTitle.textContent='สัดส่วนประเภทแบบทดสอบ';const avg=a.length?nsum(a,'average_score')/a.length:0;ins=[`คะแนนเฉลี่ยรวม ${avg.toFixed(2)}`,`ข้อมูล ${a.length.toLocaleString('th-TH')} รายการ`,subjects[0]?`วิชาเฉลี่ยสูงสุด ${subjects[0][0]}`:null]
}else if(view==='dropout'){
 const risk=entriesTop(groupCount(a,'risk_level'),10),status=entriesTop(groupCount(a,'case_status'),10);main=chartBase('bar',risk.map(x=>x[0]),risk.map(x=>x[1]),'กรณี');donut=chartBase('doughnut',status.map(x=>x[0]),status.map(x=>x[1]),'สถานะ');chartTitle.textContent='กรณีติดตามแยกระดับความเสี่ยง';donutTitle.textContent='สถานะการติดตาม';ins=[`กรณีทั้งหมด ${a.length.toLocaleString('th-TH')} รายการ`,risk[0]?`ระดับที่พบมากสุด ${risk[0][0]} ${risk[0][1]} ราย`:null,status[0]?`สถานะหลัก ${status[0][0]}`:null]
}else if(view==='budgets'){
 const byType=entriesTop(groupSum(a,'budget_type','allocated_amount'),12);main=chartBase('bar',byType.map(x=>x[0]),byType.map(x=>x[1]),'งบจัดสรร');const allocated=nsum(a,'allocated_amount'),spent=nsum(a,'spent_amount'),balance=Math.max(0,allocated-spent);donut=chartBase('doughnut',['ใช้จ่าย','คงเหลือ'],[spent,balance],'งบประมาณ');chartTitle.textContent='งบจัดสรรตามประเภทงบ';donutTitle.textContent='สัดส่วนการใช้จ่าย';const pct=allocated?spent/allocated*100:0;ins=[`จัดสรร ${allocated.toLocaleString('th-TH')} บาท`,`ใช้จ่าย ${spent.toLocaleString('th-TH')} บาท (${pct.toFixed(1)}%)`,`คงเหลือ ${balance.toLocaleString('th-TH')} บาท`]
}else if(view==='ict'){
 const devices=[['คอมพิวเตอร์',nsum(a,'computer_count')],['แท็บเล็ต',nsum(a,'tablet_count')],['Smart TV',nsum(a,'smart_tv_count')],['โปรเจกเตอร์',nsum(a,'projector_count')],['Wi-Fi',nsum(a,'wifi_points')]];main=chartBase('bar',devices.map(x=>x[0]),devices.map(x=>x[1]),'จำนวนอุปกรณ์');const internet=entriesTop(groupCount(a,'internet_status'),8);donut=chartBase('doughnut',internet.map(x=>x[0]),internet.map(x=>x[1]),'สถานะ');chartTitle.textContent='จำนวนอุปกรณ์ ICT';donutTitle.textContent='สถานะอินเทอร์เน็ต';const avg=a.length?nsum(a,'internet_speed_mbps')/a.length:0;ins=[`โรงเรียนในข้อมูล ${a.length.toLocaleString('th-TH')} แห่ง`,`ความเร็วอินเทอร์เน็ตเฉลี่ย ${avg.toFixed(1)} Mbps`,`คอมพิวเตอร์รวม ${nsum(a,'computer_count').toLocaleString('th-TH')} เครื่อง`]
}else if(view==='documents'){
 const cat=entriesTop(groupCount(a,'category'),12),active=entriesTop(groupCount(a,'active'),4);main=chartBase('bar',cat.map(x=>x[0]),cat.map(x=>x[1]),'เอกสาร');donut=chartBase('doughnut',active.map(x=>x[0]==='true'?'เผยแพร่':'ไม่เผยแพร่'),active.map(x=>x[1]),'สถานะ');chartTitle.textContent='เอกสารแยกตามหมวด';donutTitle.textContent='สถานะการเผยแพร่';ins=[`เอกสารทั้งหมด ${a.length.toLocaleString('th-TH')} รายการ`,cat[0]?`หมวดที่มีมากสุด ${cat[0][0]}`:null,'เลือกหมวดหรือค้นหาจากตารางด้านล่างได้']
}else if(view==='announcements'){
 const byMonth={};a.forEach(x=>{const d=String(x.published_date||'').slice(0,7)||'ไม่ระบุ';byMonth[d]=(byMonth[d]||0)+1});const e=Object.entries(byMonth).sort((a,b)=>a[0].localeCompare(b[0]));main=chartBase('line',e.map(x=>x[0]),e.map(x=>x[1]),'ข่าว');const st=entriesTop(groupCount(a,'active'),4);donut=chartBase('doughnut',st.map(x=>x[0]==='true'?'เผยแพร่':'ไม่เผยแพร่'),st.map(x=>x[1]),'สถานะ');chartTitle.textContent='จำนวนข่าวตามเดือน';donutTitle.textContent='สถานะข่าว';ins=[`ข่าวทั้งหมด ${a.length.toLocaleString('th-TH')} รายการ`,'กราฟปรับตามคำค้นหาและตัวกรองอัตโนมัติ','แตะกราฟเพื่อดูค่ารายละเอียด']
}else{return}
 drawDashboard(main,donut);insightLines(ins)
}catch(e){console.warn('dashboard',e)}finally{naraDashBusy=false}}
const dashObserver=new MutationObserver(()=>{clearTimeout(window.__naraDashTimer);window.__naraDashTimer=setTimeout(renderInteractiveDashboard,80)});const rc=document.getElementById('recordCount');if(rc)dashObserver.observe(rc,{childList:true,subtree:true,characterData:true});['searchBox','districtFilter','yearFilter'].forEach(id=>{const el=document.getElementById(id);if(el){el.addEventListener('input',()=>setTimeout(renderInteractiveDashboard,30));el.addEventListener('change',()=>setTimeout(renderInteractiveDashboard,30))}});setTimeout(renderInteractiveDashboard,500);