const MODULES={
Schools:{label:'โรงเรียนในสังกัด',table:'schools',sheet:'Schools',roles:['admin','area_staff'],required:['school_code','school_name','district'],conflict:'school_code'},
Students:{label:'นักเรียน',table:'students',sheet:'Students',roles:['admin','area_staff','school_admin'],required:['academic_year','student_code','school_code','first_name','last_name'],conflict:'academic_year,school_id,student_code'},
Staff:{label:'ครูและบุคลากร',table:'staff',sheet:'Staff',roles:['admin','area_staff','school_admin'],required:['employee_code','first_name','last_name','staff_type'],conflict:'employee_code'},
Retirements:{label:'ผู้เกษียณอายุราชการ',table:'retirements',sheet:'Retirements',roles:['admin','area_staff'],required:['buddhist_year','teachers','support_staff'],conflict:'buddhist_year'},
Achievement:{label:'ผลสัมฤทธิ์ทางการเรียน',table:'achievement_results',sheet:'Achievement',roles:['admin','area_staff','school_admin'],required:['academic_year','school_code','subject','grade_level','test_name'],conflict:'academic_year,school_id,subject,grade_level,test_name'},
ZeroDropout:{label:'OBEC Zero Dropout',table:'dropout_cases',sheet:'ZeroDropout',roles:['admin','area_staff','school_admin'],required:['academic_year','school_code','case_code'],conflict:'academic_year,school_id,case_code'},
Budget:{label:'งบประมาณ',table:'budgets',sheet:'Budget',roles:['admin','area_staff','school_admin'],required:['fiscal_year','budget_type','project_name'],conflict:'fiscal_year,school_id,budget_type,project_name'},
ICT:{label:'โครงสร้างพื้นฐาน / ICT',table:'ict_infrastructure',sheet:'ICT',roles:['admin','area_staff','school_admin'],required:['academic_year','school_code'],conflict:'academic_year,school_id'},
KPI:{label:'ข้อมูลภาพรวม',table:'kpi_snapshots',sheet:'KPI',roles:['admin','area_staff'],required:['academic_year','schools','students','teachers','area_staff'],conflict:'academic_year'},
Announcements:{label:'ข่าวประชาสัมพันธ์',table:'announcements',sheet:'Announcements',roles:['admin','area_staff'],required:['published_date','title'],conflict:null},
Documents:{label:'ดาวน์โหลดเอกสาร',table:'documents',sheet:'Documents',roles:['admin','area_staff'],required:['category','title','file_url'],conflict:null},
UserRoles:{label:'ตั้งค่าผู้ใช้ / สิทธิ์',table:'profiles',sheet:'UserRoles',roles:['admin'],required:['email','role'],conflict:'email'}
};
let profile=null, parsedRows=[];
const modSel=document.getElementById('module'),fileInput=document.getElementById('file'),previewBtn=document.getElementById('previewBtn'),importBtn=document.getElementById('importBtn'),clearBtn=document.getElementById('clearBtn'),summary=document.getElementById('summary'),previewTable=document.getElementById('previewTable'),permission=document.getElementById('permission'),templateInfo=document.getElementById('templateInfo');
Object.entries(MODULES).forEach(([k,v])=>{const o=document.createElement('option');o.value=k;o.textContent=v.label;modSel.appendChild(o)});
function showStatus(msg,bad=false){permission.style.display='block';permission.className='status'+(bad?' danger':'');permission.textContent=msg}
function normalizeDate(v){if(!v)return null;if(v instanceof Date)return v.toISOString().slice(0,10);if(typeof v==='number'){const d=XLSX.SSF.parse_date_code(v);if(d)return `${d.y}-${String(d.m).padStart(2,'0')}-${String(d.d).padStart(2,'0')}`}return String(v).slice(0,10)}
async function rest(path,opts={}){const r=await authFetch(`/rest/v1/${path}`,opts);let body=null;try{body=await r.json()}catch{}if(!r.ok)throw new Error(body?.message||body?.details||`HTTP ${r.status}`);return body}
async function getMaps(){const [schools,districts]=await Promise.all([rest('schools?select=id,school_code,name'),rest('districts?select=id,name')]);return {schools:new Map(schools.map(x=>[String(x.school_code),x])),districts:new Map(districts.map(x=>[String(x.name).trim(),x]))}}
function rowsFromWorkbook(wb,cfg){const ws=wb.Sheets[cfg.sheet]||wb.Sheets[wb.SheetNames[0]];if(!ws)throw new Error('ไม่พบชีตข้อมูล');let rows=XLSX.utils.sheet_to_json(ws,{defval:null,raw:false});rows=rows.filter(r=>Object.values(r).some(v=>v!==null&&v!==''));return rows}
function validate(rows,cfg){if(!rows.length)throw new Error('ไม่พบข้อมูลสำหรับนำเข้า');const cols=Object.keys(rows[0]);const missing=cfg.required.filter(c=>!cols.includes(c));if(missing.length)throw new Error('ขาดคอลัมน์บังคับ: '+missing.join(', '));return cols}
function renderPreview(rows,cols){summary.textContent=`พบ ${rows.length.toLocaleString('th-TH')} แถว • ${cols.length} คอลัมน์ • แสดงตัวอย่างสูงสุด 20 แถว`;previewTable.innerHTML='<thead><tr>'+cols.map(c=>`<th>${c}</th>`).join('')+'</tr></thead><tbody>'+rows.slice(0,20).map(r=>'<tr>'+cols.map(c=>`<td>${r[c]??''}</td>`).join('')+'</tr>').join('')+'</tbody>'}
async function transformRows(rows,key){const cfg=MODULES[key],maps=await getMaps();const out=[];for(const raw of rows){const r={...raw};if(key==='Schools'){const d=maps.districts.get(String(r.district||'').trim());if(!d)throw new Error(`ไม่พบอำเภอ: ${r.district}`);out.push({school_code:String(r.school_code),name:r.school_name,district_id:d.id,address:r.address||null,subdistrict:r.subdistrict||null,phone:r.phone||null,email:r.email||null,student_count:+(r.student_count||0),teacher_count:+(r.teacher_count||0),active:String(r.active).toLowerCase()!=='false'});continue}
if(['Students','Achievement','ZeroDropout','Budget','ICT'].includes(key)||key==='Staff'){
 let school=null;if(r.school_code){school=maps.schools.get(String(r.school_code));if(!school)throw new Error(`ไม่พบรหัสโรงเรียน: ${r.school_code}`)}
 if(profile.role==='school_admin'&&school?.id!==profile.school_id)throw new Error(`ไม่มีสิทธิ์นำเข้าข้อมูลโรงเรียน ${r.school_code}`);
 r.school_id=school?.id||null;delete r.school_code;
}
if(key==='Students')out.push({academic_year:+r.academic_year,student_code:String(r.student_code),school_id:r.school_id,prefix:r.prefix||null,first_name:r.first_name,last_name:r.last_name,gender:r.gender||null,grade_level:r.grade_level||null,classroom:r.classroom||null,status:r.status||'active'});
else if(key==='Staff')out.push({employee_code:String(r.employee_code),prefix:r.prefix||null,first_name:r.first_name,last_name:r.last_name,position:r.position||null,staff_type:r.staff_type||'teacher',school_id:r.school_id,birth_date:normalizeDate(r.birth_date),retirement_date:normalizeDate(r.retirement_date),status:r.status||'active'});
else if(key==='Retirements')out.push({buddhist_year:+r.buddhist_year,teachers:+(r.teachers||0),support_staff:+(r.support_staff||0),is_demo:String(r.is_demo).toLowerCase()==='true'});
else if(key==='Achievement')out.push({academic_year:+r.academic_year,school_id:r.school_id,subject:r.subject,grade_level:r.grade_level,test_name:r.test_name,average_score:r.average_score===''||r.average_score==null?null:+r.average_score,student_count:+(r.student_count||0),full_score:r.full_score===''||r.full_score==null?null:+r.full_score});
else if(key==='ZeroDropout')out.push({academic_year:+r.academic_year,school_id:r.school_id,case_code:String(r.case_code),student_code:r.student_code?String(r.student_code):null,case_status:r.case_status||'open',risk_level:r.risk_level||null,reason:r.reason||null,followup_date:normalizeDate(r.followup_date),notes:r.notes||null});
else if(key==='Budget')out.push({fiscal_year:+r.fiscal_year,school_id:r.school_id,budget_type:r.budget_type,project_name:r.project_name,allocated_amount:+(r.allocated_amount||0),spent_amount:+(r.spent_amount||0),status:r.status||'active'});
else if(key==='ICT')out.push({academic_year:+r.academic_year,school_id:r.school_id,internet_status:r.internet_status||null,internet_speed_mbps:r.internet_speed_mbps===''||r.internet_speed_mbps==null?null:+r.internet_speed_mbps,computer_count:+(r.computer_count||0),tablet_count:+(r.tablet_count||0),smart_tv_count:+(r.smart_tv_count||0),projector_count:+(r.projector_count||0),wifi_points:+(r.wifi_points||0),notes:r.notes||null});
else if(key==='KPI')out.push({academic_year:+r.academic_year,schools:+r.schools,students:+r.students,teachers:+r.teachers,area_staff:+r.area_staff,is_demo:String(r.is_demo).toLowerCase()==='true'});
else if(key==='Announcements')out.push({published_date:normalizeDate(r.published_date),title:r.title,active:String(r.active).toLowerCase()!=='false'});
else if(key==='Documents')out.push({category:r.category,title:r.title,file_url:r.file_url,published_date:normalizeDate(r.published_date)||new Date().toISOString().slice(0,10),active:String(r.active).toLowerCase()!=='false'});
else if(key==='UserRoles')out.push({email:String(r.email).toLowerCase(),display_name:r.display_name||null,role:r.role,school_code:r.school_code||null});
}
return out}
async function importRows(rows,key){const cfg=MODULES[key];if(key==='UserRoles'){const maps=await getMaps();for(const r of rows){if(!['admin','area_staff','school_admin','viewer'].includes(r.role))throw new Error(`role ไม่ถูกต้อง: ${r.role}`);const sid=r.school_code?maps.schools.get(String(r.school_code))?.id:null;if(r.role==='school_admin'&&!sid)throw new Error(`school_admin ต้องมี school_code ที่ถูกต้อง: ${r.email}`);const q=`profiles?email=eq.${encodeURIComponent(r.email)}`;const found=await rest(q);if(!found.length)throw new Error(`ยังไม่มีบัญชี Auth สำหรับ ${r.email}`);await rest(`profiles?id=eq.${found[0].id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({display_name:r.display_name||found[0].display_name,role:r.role,school_id:sid})})}return rows.length}
const headers={Prefer:cfg.conflict?'resolution=merge-duplicates,return=minimal':'return=minimal'};if(cfg.conflict)headers['Prefer']+=`;`;const url=cfg.conflict?`${cfg.table}?on_conflict=${encodeURIComponent(cfg.conflict)}`:cfg.table;await rest(url,{method:'POST',headers,body:JSON.stringify(rows)});return rows.length}
async function updateModuleInfo(){const cfg=MODULES[modSel.value],allowed=cfg.roles.includes(profile?.role);showStatus(allowed?`สิทธิ์ปัจจุบัน: ${roleLabel(profile.role)} • สามารถนำเข้า ${cfg.label} ได้`:`สิทธิ์ปัจจุบัน: ${roleLabel(profile?.role)} • ไม่มีสิทธิ์นำเข้า ${cfg.label}`,!allowed);templateInfo.innerHTML=`ชีต: <b>${cfg.sheet}</b><br>คอลัมน์บังคับ: <b>${cfg.required.join(', ')}</b><br>โหมดบันทึก: <b>${cfg.conflict?'Upsert (เพิ่มใหม่หรืออัปเดตข้อมูลเดิม)':'เพิ่มรายการใหม่'}</b>`;importBtn.disabled=true;parsedRows=[];previewTable.innerHTML='';summary.textContent='ยังไม่ได้เลือกไฟล์'}
previewBtn.onclick=async()=>{try{const cfg=MODULES[modSel.value];if(!cfg.roles.includes(profile.role))throw new Error('ไม่มีสิทธิ์นำเข้าด้านนี้');const file=fileInput.files[0];if(!file)throw new Error('กรุณาเลือกไฟล์ Excel');const buf=await file.arrayBuffer(),wb=XLSX.read(buf,{type:'array',cellDates:true});const rows=rowsFromWorkbook(wb,cfg);const cols=validate(rows,cfg);parsedRows=await transformRows(rows,modSel.value);renderPreview(rows,cols);importBtn.disabled=false;showStatus(`ตรวจสอบผ่าน ${parsedRows.length} แถว พร้อมนำเข้า`)}catch(e){importBtn.disabled=true;showStatus(e.message,true)}};
importBtn.onclick=async()=>{try{if(!parsedRows.length)throw new Error('ยังไม่มีข้อมูลที่ตรวจสอบแล้ว');importBtn.disabled=true;showStatus('กำลังนำเข้าข้อมูล...');const n=await importRows(parsedRows,modSel.value);showStatus(`นำเข้าสำเร็จ ${n.toLocaleString('th-TH')} แถว`);parsedRows=[]}catch(e){showStatus('นำเข้าไม่สำเร็จ: '+e.message,true);importBtn.disabled=false}};
clearBtn.onclick=()=>{fileInput.value='';parsedRows=[];previewTable.innerHTML='';summary.textContent='ยังไม่ได้เลือกไฟล์';importBtn.disabled=true};modSel.onchange=updateModuleInfo;
(async()=>{profile=await requireAuth(['admin','area_staff','school_admin']);if(!profile)return;await updateModuleInfo()})();