const qs=new URLSearchParams(location.search),view=qs.get('view')||'overview';
const SB='https://pjzgoqbnbqwqacyyvzxa.supabase.co',KEY='sb_publishable_J8tgwn1RxrQLU2OjF8dXFg_1ngKSdho';
const configs={
 overview:{title:'ข้อมูลภาพรวม',desc:'สรุปข้อมูลสำคัญของ สพป.นราธิวาส เขต 2'},
 schools:{title:'โรงเรียนในสังกัด',desc:'ข้อมูลโรงเรียนในสังกัดทั้งหมด',table:'schools',select:'id,school_code,name,district_id,address,subdistrict,phone,email,student_count,teacher_count,active,districts(name)',cols:[['school_code','รหัส'],['name','โรงเรียน'],['district','อำเภอ'],['address','ที่อยู่'],['subdistrict','ตำบล'],['phone','โทรศัพท์'],['email','อีเมล'],['student_count','นักเรียน'],['teacher_count','ครู'],['active','สถานะ']],fields:[['school_code','รหัสโรงเรียน','text'],['name','ชื่อโรงเรียน','text'],['district_id','อำเภอ','district'],['address','ที่อยู่','text'],['subdistrict','ตำบล','text'],['phone','โทรศัพท์','text'],['email','อีเมล','email'],['student_count','จำนวนนักเรียน','number'],['teacher_count','จำนวนครู','number'],['active','เปิดใช้งาน','boolean']]},
 students:{title:'ข้อมูลนักเรียน',desc:'ข้อมูลนักเรียนทั้งหมดในระบบ',table:'students',select:'id,academic_year,student_code,school_id,prefix,first_name,last_name,gender,grade_level,classroom,status,schools(name,school_code)',cols:[['academic_year','ปีการศึกษา'],['student_code','รหัสนักเรียน'],['school','โรงเรียน'],['prefix','คำนำหน้า'],['first_name','ชื่อ'],['last_name','นามสกุล'],['gender','เพศ'],['grade_level','ชั้น'],['classroom','ห้อง'],['status','สถานะ']],fields:[['academic_year','ปีการศึกษา','number'],['student_code','รหัสนักเรียน','text'],['school_id','โรงเรียน','school'],['prefix','คำนำหน้า','text'],['first_name','ชื่อ','text'],['last_name','นามสกุล','text'],['gender','เพศ','text'],['grade_level','ระดับชั้น','text'],['classroom','ห้อง','text'],['status','สถานะ','text']]},
 staff:{title:'ครูและบุคลากร',desc:'ข้อมูลครูและบุคลากรทั้งหมดในระบบ',table:'staff',select:'id,employee_code,prefix,first_name,last_name,position,staff_type,school_id,birth_date,retirement_date,status,schools(name,school_code)',cols:[['employee_code','รหัสบุคลากร'],['prefix','คำนำหน้า'],['first_name','ชื่อ'],['last_name','นามสกุล'],['position','ตำแหน่ง'],['staff_type','ประเภท'],['school','โรงเรียน'],['birth_date','วันเกิด'],['retirement_date','วันเกษียณ'],['status','สถานะ']],fields:[['employee_code','รหัสบุคลากร','text'],['prefix','คำนำหน้า','text'],['first_name','ชื่อ','text'],['last_name','นามสกุล','text'],['position','ตำแหน่ง','text'],['staff_type','ประเภทบุคลากร','text'],['school_id','โรงเรียน','school'],['birth_date','วันเกิด','date'],['retirement_date','วันเกษียณ','date'],['status','สถานะ','text']]},
 retirements:{title:'ผู้เกษียณอายุราชการ',desc:'ข้อมูลผู้เกษียณรายปี',table:'retirements',select:'id,buddhist_year,teachers,support_staff,is_demo',cols:[['buddhist_year','ปี พ.ศ.'],['teachers','ครู'],['support_staff','สายสนับสนุน'],['total','รวม'],['is_demo','ประเภทข้อมูล']],fields:[['buddhist_year','ปี พ.ศ.','number'],['teachers','จำนวนครู','number'],['support_staff','จำนวนสายสนับสนุน','number'],['is_demo','ข้อมูลสาธิต','boolean']]},
 achievement:{title:'ผลสัมฤทธิ์ทางการเรียน',desc:'ข้อมูลผลสัมฤทธิ์ทางการเรียนทุกโรงเรียน',table:'achievement_results',select:'id,academic_year,school_id,subject,grade_level,test_name,average_score,student_count,full_score,schools(name,school_code)',cols:[['academic_year','ปี'],['school','โรงเรียน'],['subject','วิชา'],['grade_level','ชั้น'],['test_name','แบบทดสอบ'],['average_score','คะแนนเฉลี่ย'],['student_count','ผู้เข้าสอบ'],['full_score','คะแนนเต็ม']],fields:[['academic_year','ปีการศึกษา','number'],['school_id','โรงเรียน','school'],['subject','วิชา','text'],['grade_level','ระดับชั้น','text'],['test_name','ชื่อแบบทดสอบ','text'],['average_score','คะแนนเฉลี่ย','number'],['student_count','จำนวนผู้เข้าสอบ','number'],['full_score','คะแนนเต็ม','number']]},
 dropout:{title:'OBEC Zero Dropout',desc:'ข้อมูลติดตามนักเรียนรายกรณี',table:'dropout_cases',select:'id,academic_year,school_id,case_code,student_code,case_status,risk_level,reason,followup_date,notes,schools(name,school_code)',cols:[['academic_year','ปี'],['school','โรงเรียน'],['case_code','รหัสกรณี'],['student_code','รหัสนักเรียน'],['case_status','สถานะ'],['risk_level','ระดับความเสี่ยง'],['reason','สาเหตุ'],['followup_date','ติดตามวันที่'],['notes','หมายเหตุ']],fields:[['academic_year','ปีการศึกษา','number'],['school_id','โรงเรียน','school'],['case_code','รหัสกรณี','text'],['student_code','รหัสนักเรียน','text'],['case_status','สถานะกรณี','text'],['risk_level','ระดับความเสี่ยง','text'],['reason','สาเหตุ','text'],['followup_date','วันที่ติดตาม','date'],['notes','หมายเหตุ','textarea']]},
 budgets:{title:'งบประมาณ',desc:'ข้อมูลงบประมาณและการใช้จ่าย',table:'budgets',select:'id,fiscal_year,school_id,budget_type,project_name,allocated_amount,spent_amount,status,schools(name,school_code)',cols:[['fiscal_year','ปีงบประมาณ'],['school','โรงเรียน'],['budget_type','ประเภทงบ'],['project_name','โครงการ'],['allocated_amount','จัดสรร'],['spent_amount','ใช้จ่าย'],['balance','คงเหลือ'],['status','สถานะ']],fields:[['fiscal_year','ปีงบประมาณ','number'],['school_id','โรงเรียน','school'],['budget_type','ประเภทงบ','text'],['project_name','ชื่อโครงการ','text'],['allocated_amount','งบจัดสรร','number'],['spent_amount','ใช้จ่าย','number'],['status','สถานะ','text']]},
 ict:{title:'โครงสร้างพื้นฐาน / ICT',desc:'ข้อมูลอินเทอร์เน็ตและอุปกรณ์เทคโนโลยี',table:'ict_infrastructure',select:'id,academic_year,school_id,internet_status,internet_speed_mbps,computer_count,tablet_count,smart_tv_count,projector_count,wifi_points,notes,schools(name,school_code)',cols:[['academic_year','ปี'],['school','โรงเรียน'],['internet_status','อินเทอร์เน็ต'],['internet_speed_mbps','ความเร็ว Mbps'],['computer_count','คอมพิวเตอร์'],['tablet_count','แท็บเล็ต'],['smart_tv_count','Smart TV'],['projector_count','โปรเจกเตอร์'],['wifi_points','Wi-Fi'],['notes','หมายเหตุ']],fields:[['academic_year','ปีการศึกษา','number'],['school_id','โรงเรียน','school'],['internet_status','สถานะอินเทอร์เน็ต','text'],['internet_speed_mbps','ความเร็ว Mbps','number'],['computer_count','คอมพิวเตอร์','number'],['tablet_count','แท็บเล็ต','number'],['smart_tv_count','Smart TV','number'],['projector_count','โปรเจกเตอร์','number'],['wifi_points','จุด Wi-Fi','number'],['notes','หมายเหตุ','textarea']]},
 documents:{title:'ดาวน์โหลดเอกสาร',desc:'คลังเอกสารและไฟล์เผยแพร่',table:'documents',select:'id,category,title,file_url,published_date,active',cols:[['category','หมวด'],['title','ชื่อเอกสาร'],['file_url','ลิงก์ไฟล์'],['published_date','วันที่เผยแพร่'],['active','สถานะ']],fields:[['category','หมวดเอกสาร','text'],['title','ชื่อเอกสาร','text'],['file_url','ลิงก์ไฟล์','url'],['published_date','วันที่เผยแพร่','date'],['active','เผยแพร่','boolean']]},
 announcements:{title:'ข่าวประชาสัมพันธ์',desc:'ข่าวและประกาศของระบบ',table:'announcements',select:'id,published_date,title,active',cols:[['published_date','วันที่'],['title','หัวข้อ'],['active','สถานะ']],fields:[['published_date','วันที่เผยแพร่','date'],['title','หัวข้อข่าว','text'],['active','เผยแพร่','boolean']]}
};
const cfg=configs[view]||configs.overview;let rows=[],filtered=[],profile=null,schools=[],districts=[],settings=null,editingId=null;
pageTitle.textContent=cfg.title;pageDesc.textContent=cfg.desc;pageBadge.textContent='ข้อมูลสาธารณะ';panelTitle.textContent=cfg.title;
const fmt=n=>Number(n||0).toLocaleString('th-TH');const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
async function pub(table,q=''){const r=await fetch(`${SB}/rest/v1/${table}?${q}`,{headers:{apikey:KEY,Authorization:`Bearer ${KEY}`}});if(!r.ok)throw new Error(await r.text());return r.json()}
function normalize(r){const x={...r};if(r.districts)x.district=r.districts.name;if(r.schools)x.school=r.schools.name;if(view==='retirements')x.total=(+r.teachers||0)+(+r.support_staff||0);if(view==='budgets')x.balance=(+r.allocated_amount||0)-(+r.spent_amount||0);return x}
function card(label,value,unit=''){return `<div class="mini"><small>${esc(label)}</small><b>${fmt(value)}</b><span>${esc(unit)}</span></div>`}
function visibleCols(){if(settings?.visible_columns?.length){const allowed=new Set(settings.visible_columns);return cfg.cols.filter(([k])=>allowed.has(k))}return cfg.cols||[]}
function renderTable(){const cols=visibleCols();recordCount.textContent=`${fmt(filtered.length)} รายการ`;content.innerHTML=`<div class="table-wrap"><table class="data-table"><thead><tr>${cols.map(c=>`<th>${esc(c[1])}</th>`).join('')}${profile?.role==='admin'?'<th>จัดการ</th>':''}</tr></thead><tbody>${filtered.map(r=>`<tr>${cols.map(([k])=>`<td>${cell(k,r[k])}</td>`).join('')}${profile?.role==='admin'?`<td><div class="row-actions"><button onclick="editRow(${r.id})">แก้ไข</button><button onclick="deleteRow(${r.id})">ลบ</button></div></td>`:''}</tr>`).join('')}</tbody></table></div>`}
function cell(k,v){if(k==='file_url'&&v)return `<a href="${esc(v)}" target="_blank" rel="noopener">เปิดไฟล์</a>`;if(typeof v==='boolean')return v?'ใช้งาน':'ปิด';if(['student_count','teacher_count','teachers','support_staff','total','average_score','full_score','allocated_amount','spent_amount','balance','internet_speed_mbps','computer_count','tablet_count','smart_tv_count','projector_count','wifi_points'].includes(k))return fmt(v);if(k==='is_demo')return v?'ข้อมูลสาธิต':'ข้อมูลจริง';return esc(v||'-')}
function applyFilters(){const q=searchBox.value.trim().toLowerCase(),d=districtFilter.value,y=yearFilter.value;filtered=rows.filter(r=>{const txt=Object.values(normalize(r)).filter(v=>typeof v!=='object').join(' ').toLowerCase();const districtName=r.districts?.name||r.schools?.districts?.name||'';const year=r.academic_year||r.fiscal_year||r.buddhist_year||'';return(!q||txt.includes(q))&&(!d||districtName===d)&&(!y||String(year)===y)}).map(normalize);renderTable()}
function setupFilters(){districtFilter.innerHTML='<option value="">ทุกอำเภอ</option>'+districts.map(d=>`<option>${esc(d.name)}</option>`).join('');const ys=[...new Set(rows.map(r=>r.academic_year||r.fiscal_year||r.buddhist_year).filter(Boolean))].sort((a,b)=>b-a);yearFilter.innerHTML='<option value="">ทุกปี</option>'+ys.map(y=>`<option>${y}</option>`).join('');districtFilter.style.display=['schools','students','staff','achievement','dropout','budgets','ict'].includes(view)?'block':'none';yearFilter.style.display=ys.length?'block':'none';searchBox.oninput=applyFilters;districtFilter.onchange=applyFilters;yearFilter.onchange=applyFilters}
async function loadBase(){[schools,districts]=await Promise.all([pub('schools','select=id,school_code,name,district_id,districts(name)&order=name'),pub('districts','select=id,name&order=id')]);try{settings=(await pub('module_settings',`module_key=eq.${view}&select=*`))[0]||null}catch{} }
async function load(){try{const k=(await pub('kpi_snapshots','select=*&order=academic_year.desc&limit=1'))[0]||{};cards.innerHTML=card('โรงเรียน',k.schools,' โรงเรียน')+card('นักเรียน',k.students,' คน')+card('ครู',k.teachers,' คน')+card('บุคลากรเขต',k.area_staff,' คน');if(view==='overview'){districtFilter.style.display=yearFilter.style.display=searchBox.style.display='none';const ds=await pub('districts','select=name,school_count&order=id');content.innerHTML=`<div class="table-wrap"><table class="data-table"><thead><tr><th>อำเภอ</th><th>จำนวนโรงเรียน</th></tr></thead><tbody>${ds.map(x=>`<tr><td>${esc(x.name)}</td><td>${fmt(x.school_count)}</td></tr>`).join('')}</tbody></table></div>`;recordCount.textContent=`${ds.length} อำเภอ`;return}await loadBase();rows=await pub(cfg.table,`select=${encodeURIComponent(cfg.select)}&order=id`);setupFilters();applyFilters()}catch(e){content.innerHTML='<div class="loading">ไม่สามารถโหลดข้อมูลได้ กรุณาลองใหม่อีกครั้ง</div>';console.error(e)}}
function fieldHtml([key,label,type],value=''){if(type==='school')return `<label>${label}<select name="${key}"><option value="">ไม่ระบุ</option>${schools.map(s=>`<option value="${s.id}" ${String(value)===String(s.id)?'selected':''}>${esc(s.name)}</option>`).join('')}</select></label>`;if(type==='district')return `<label>${label}<select name="${key}">${districts.map(d=>`<option value="${d.id}" ${String(value)===String(d.id)?'selected':''}>${esc(d.name)}</option>`).join('')}</select></label>`;if(type==='boolean')return `<label>${label}<select name="${key}"><option value="true" ${value===true?'selected':''}>ใช่</option><option value="false" ${value===false?'selected':''}>ไม่ใช่</option></select></label>`;if(type==='textarea')return `<label>${label}<textarea name="${key}">${esc(value||'')}</textarea></label>`;return `<label>${label}<input name="${key}" type="${type}" value="${esc(value??'')}"></label>`}
function openForm(row=null){editingId=row?.id||null;modalTitle.textContent=editingId?'แก้ไขข้อมูล':'เพิ่มข้อมูล';formFields.innerHTML=(cfg.fields||[]).map(f=>fieldHtml(f,row?.[f[0]])).join('');editModal.classList.add('show')}
function closeForm(){editModal.classList.remove('show');editingId=null;dataForm.reset()}
window.editRow=id=>{const r=rows.find(x=>x.id===id);if(r)openForm(r)};
window.deleteRow=async id=>{if(profile?.role!=='admin'||!confirm('ยืนยันการลบข้อมูลรายการนี้?'))return;const r=await authFetch(`/rest/v1/${cfg.table}?id=eq.${id}`,{method:'DELETE',headers:{Prefer:'return=minimal'}});showStatus(r.ok?'ลบข้อมูลเรียบร้อย':'ลบข้อมูลไม่สำเร็จ');if(r.ok)await reloadRows()};
function showStatus(t){status.textContent=t;status.style.display='block';setTimeout(()=>status.style.display='none',3500)}
async function reloadRows(){rows=await pub(cfg.table,`select=${encodeURIComponent(cfg.select)}&order=id`);setupFilters();applyFilters()}
async function initUser(){const s=getSession();if(!s){sectionUser.innerHTML='<a class="btn" href="login.html">เข้าสู่ระบบจัดการข้อมูล</a>';return}try{profile=await getMyProfile()}catch{}if(profile){sectionUser.innerHTML=`<span style="font-size:13px;color:#52697f">${esc(profile.display_name||'')} • ${esc(roleLabel(profile.role))}</span>`;if(profile.role==='admin'&&cfg.table){adminTools.classList.add('show');addBtn.onclick=()=>openForm()}}}
closeModal.onclick=cancelBtn.onclick=closeForm;editModal.onclick=e=>{if(e.target===editModal)closeForm()};
dataForm.onsubmit=async e=>{e.preventDefault();if(profile?.role!=='admin')return;const fd=new FormData(dataForm),body={};for(const [key,,type] of cfg.fields){let v=fd.get(key);if(type==='number')v=v===''?null:Number(v);else if(type==='boolean')v=v==='true';else if(type==='school'||type==='district')v=v?Number(v):null;body[key]=v===''?null:v}const path=editingId?`/rest/v1/${cfg.table}?id=eq.${editingId}`:`/rest/v1/${cfg.table}`;const r=await authFetch(path,{method:editingId?'PATCH':'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(body)});if(r.ok){showStatus(editingId?'แก้ไขข้อมูลเรียบร้อย':'เพิ่มข้อมูลเรียบร้อย');closeForm();await reloadRows()}else{showStatus('บันทึกไม่สำเร็จ: '+await r.text())}};
(async()=>{await initUser();await load()})();